version: '3.8'

services:
  backend:
    build: ./backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
      - media_data:/app/media
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
      - media_data:/usr/share/nginx/html/media:ro
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  media_data: